#配置提供者ID
spring:
  application:
    name: empsys-provider
    #配置datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empsysdb?serverTimezone=UTC
    username: root
    password: root
    #redis
  redis:
    port: 1212
    host: 192.168.31.128
    lettuce:
      pool:
        max-active: 50
        max-wait: 10000ms
        max-idle: 8
        min-idle: 5
      database: 5  #选择五号库进行数据的存储

#dubbo
#扫描暴露接口的包
dubbo:
  scan:
    base-packages: org.lanqiao.empsys.service
  registry:
    address: zookeeper://192.168.31.128:2181
    timeout: 50000
#mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  supportMethodsArguments: true
  returnPageInfo: true
  params: count=countSql
#日志
#logging:
#  level:
  #  root: INFO
  #  #    com.lanqiao.empsys.dao: DEBUG
    # 日志文件
    #    path: /Users/jamesmac/projects/SpringBootProjects/springboot-tutorials
 # pattern:
 #  3 file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
  #  console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
